### PR TITLE
Added Bootstrap and Tailwind

### PR DESCRIPTION
**Pull request by ransTomTer**
_Installed them on root node_modules_

### Installed Tailwind

Configured the tailwind 
https://stackoverflow.com/questions/62688037/can-use-both-tailwind-css-and-bootstrap-4-at-the-same-time
image

The custom configuration made the tailwind classes need a `tw-` prefix 
Here is an example
image

---

I also updated vite configuration to listen for changes in 
image

Then example declaration of stylesheet or script
image

Then on current project run on terminal the `npm run dev`
This allow hot reloading when saving changes

---
Installed bootstrap 5.3.3

I also customized bootstrap colors
image
Customization to font size were not included due to error when set a custom value

### CODE REVIEW

**Comment by ransTomTer** [comment]
Here is my live sass compiler configuration

image

**Review by Carl-Tabuso — APPROVED** [review]
Tagging this as important

**Comment by C-Ivan-Bandilla** [comment]
Still figuring out how to config and use tailwind if custom installed to vendor folder

**Comment by C-Ivan-Bandilla** [comment]
Bootstrap and Tailwind are now on **vendor** package.json

However, I wasn’t able to configure Tailwind CSS to work.
Currently, there is limited or not easily comprehensible documentation and resources will try to fix on other pr

**Pull request merged**
