### PR TITLE
Applicant/signup

### PR DESCRIPTION
**Pull request by C-Ivan-Bandilla**
### Fix to livewire csp policy
I manage to allow injected livewire inline script execution by adding nonce hash to the livewire component (wala sa official documentation)
image

### Added search functionality
https://github.com/user-attachments/assets/ba20eb23-3819-48d2-8894-c4c496532e62

### Added sign up form 
https://drive.google.com/file/d/1fHtkNW7lVQU0wg4UlEEoGO7fzUc19F0D/view?usp=sharing

- The backend is functional
- The front end is not yet finished
- Some frontend elements are not visible due to converting signup form to livewire component
- The laravel debugbar mess with fetching data of valid emails used for client side validation of email
image

### CODE REVIEW

**Comment by C-Ivan-Bandilla** [comment]
I fetch the valid emails using a api route
image
image
image

**Comment by C-Ivan-Bandilla** [comment]
I also used a library of bad passwords in https://github.com/cry/nbp

It doesn't conform to es6 standard so I want able to import it in a js module

so instead I pasted a copy on public\build\assets
image
I think its searching algorithm is efficient tho since it search in 1 million password list although the list is last updated 8 years ago


Also laravel also provide validation of weak password for serverside validation

**Comment by C-Ivan-Bandilla** [comment]
I also registered custom validation here
image

USAGE
```
$this->validate([
            'email' => 'required|email:rfc,dns,spoof|max:255|unique:users|valid_email_dns',
            'password' => [
                'required',
                Password::defaults()
            ],
            'consent' => 'accepted',
        ]);
```

**Comment by C-Ivan-Bandilla** [comment]
Jquery can be loaded as below

`@vite(['vendor/node_modules/jquery/dist/jquery.min.js', 'vendor/node_modules/jquery/dist/jquery.slim.min.js'])`

choose slim or full minified package if depending on usage

**Review by Carl-Tabuso — COMMENTED** [review]
Can you add the length for each table field in each migration files?

Like
```php
$table->string('name', 191);
```

Found the above example in [laracast discussion](https://laracasts.com/discuss/channels/general-discussion/migrations-configure-a-default-string-length-utf8mb4)

After which, we merge this. I need this changes before installing laravel socialite #11. Just to make sure i don't break anything.

**Comment by C-Ivan-Bandilla** [comment]
> Can you add the length for each table field in each migration files?

Should I put 255 for varchars or are there updated database schema I can reference for length?

**Comment by C-Ivan-Bandilla** [comment]
image
image

**Comment by Carl-Tabuso** [comment]
To be honest, I don't know the proper length we should assign to each fillable fields. Perhaps a little bit of research if there are any standards or best practices but that could come later. In the meantime, this works fine.

**Review by Carl-Tabuso — APPROVED** [review]

**Pull request merged**
