### PR TITLE
feat(auth): sign-in via facebook consent screen

### PR DESCRIPTION
**Pull request by Carl-Tabuso**
Had to close PR #48 due to a bunch of changes.

## Chore

- I added a new attribute/column `facebook_id` in `users` table for storage of payload return by facebook.
- I encapsulated the `handleCallback()` method in try-catch for both google and facebook.
- For safety measures, I made use of laravel's [DB facade](https://laravel.com/docs/11.x/database#manually-using-transactions) so that we can rollback the insertion if an exception occurs.
- Instead of arrays for handling google payload, I opted using collection. They say that it's the "best practice" for working with data structures since we can chain methods to it.
- In [`config/services.php`](https://github.com/POWERLANE-TEAM/emplo-hrms/blob/4e416bbb9492dbccb015868a496bc60e54862a86/config/services.php), the names are defined for accessing facebook's provided API keys, which I will provide for our `.env` file.

## Feature

- Guest users may now sign-in through their facebook account.

https://github.com/user-attachments/assets/9a8f0ac1-8382-405b-87fe-b3018b92ba23

On a side note, it's getting annoying that some of us still encounter this problem with Vite and npm. I'm considering docker to make sure we're all working with the same libraries, dependencies versions, and whatever, so that PRs aren't bloated or so heavy because of some accidental updates in dependencies.

### CODE REVIEW

**Review by C-Ivan-Bandilla — APPROVED** [review]
Just read some changes and tried the facebook sign up
Its working on the video I think it works just encountered a problem on my end

https://github.com/user-attachments/assets/5c1df4e4-fd82-4e32-86c1-f593e23c1896


---
If you encountered this try npm run build
image

**Comment by Carl-Tabuso** [comment]
I'll try the steps of the highest voted answer on this thread. Tell me if this resolves your issue.

https://stackoverflow.com/questions/73193526/app-not-active-this-app-is-not-currently-accessible-and-the-app-developer-is-aw

**Comment by Carl-Tabuso** [comment]
Can you try again @C-Ivan-Bandilla

**Comment by C-Ivan-Bandilla** [comment]
> Can you try again @C-Ivan-Bandilla

The issue still persist

Do I need permission
image
image

**Comment by Carl-Tabuso** [comment]
I'll add you as administrator. Can you give me your name/fbid/username (as many as u want)

image

**Comment by C-Ivan-Bandilla** [comment]
I ony have one account I dunno where to find fb_id you can try the following let me know if it didn't work

name Ivan Bandilla
fbid 
username IvanBandilla.00PERSONAL

**Comment by Carl-Tabuso** [comment]
image

**Comment by C-Ivan-Bandilla** [comment]
https://drive.google.com/file/d/14Ngk7ihdfYdG_nQZWMUWsUFcEe2KiAPU/view?usp=sharing

On Laravel.log
[previous exception] [object] (PDOException(code: 23502): SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column \"email\" of relation \"users\" violates not-null constraint
DETAIL:  Failing row contains (14, guest, 1, null, $2y$12$SY9pdelwLfbZyqrmyngBHeM3ihq0AnsEl0Q7swcDDf4JynQdD.aji, null, null, 3789388064722881, 1, null, null, null, null, null, 2024-10-10 05:32:03, 2024-10-10 05:32:03, null). at C:\\DevPackage\\xampp\\htdocs\\facebook\\emplo-hrms\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:412)

**Comment by C-Ivan-Bandilla** [comment]
> https://drive.google.com/file/d/14Ngk7ihdfYdG_nQZWMUWsUFcEe2KiAPU/view?usp=sharing
> 
> On Laravel.log [previous exception] [object] (PDOException(code: 23502): SQLSTATE[23502]: Not null violation: 7 ERROR: null value in column "email" of relation "users" violates not-null constraint DETAIL: Failing row contains (14, guest, 1, null, $2y$12$SY9pdelwLfbZyqrmyngBHeM3ihq0AnsEl0Q7swcDDf4JynQdD.aji, null, null, 3789388064722881, 1, null, null, null, null, null, 2024-10-10 05:32:03, 2024-10-10 05:32:03, null). at C:\DevPackage\xampp\htdocs\facebook\emplo-hrms\vendor\laravel\framework\src\Illuminate\Database\Connection.php:412)

Wait I read some article that unconfirmed email may not let facebook share the unverified email

**Comment by Carl-Tabuso** [comment]
sorry for late feedback. My workaround for this is to use null as fallback value if fb's payload->email is null.

```php
'email' => $this->payload->getEmail() ?? null,
```

**Comment by Carl-Tabuso** [comment]
sorry for late feedback. My workaround for this is to use null as fallback value if fb's payload->email is null.

```php
'email' => $this->payload->getEmail() ?? null,
```

**Comment by C-Ivan-Bandilla** [comment]
Would this work? there is not null constraint in the table

I think the null email in guest shall be allowed only if facebook_id has value 
> 
> ```
> 'email' => $this->payload->getEmail() ?? null,
> ```
>

**Comment by Carl-Tabuso** [comment]
I am yet to push the changes in the migration file.

```php
$table->string('email', 320)->unique()->nullable();
```

If a user signs-in through fb, we can always get and store the payload id in `facebook_id` column.

```php
'facebook_id' => $this->payload->getId(),
```

**Comment by Carl-Tabuso** [comment]
I'll merge this promptly if everything works fine on your end.

**Comment by C-Ivan-Bandilla** [comment]
Creation of account and login through fb is now working

Is the goggle sign up still working on your end?

[2024-10-10 09:27:26] local.ERROR: Property [given_name] does not exist on this collection instance. {"exception":"[object] (Exception(code: 0): Property [given_name] does not exist on this collection instance. at C:\\DevPackage\\xampp\\htdocs\\facebook\\emplo-hrms\\vendor\\laravel\\framework\\src\\Illuminate\\Collections\\Traits\\EnumeratesValues.php:1036)

**Comment by Carl-Tabuso** [comment]
Found the issue. I forgot to use the `get()` method for accessing each field since I converted the payload from the array into a collection instance.

before:
```php
// createGuest()

'first_name' => $payload->given_name ?? PlaceholderString::NOT_PROVIDED,
 'last_name' => $payload->family_name ?? PlaceholderString::NOT_PROVIDED,

// createUserAccount()

'email' => $payload->email,
'photo' => $payload->picture ?? null,
'google_id' => $payload->sub,

```
after:
```php
// createGuest()

'first_name' => $payload->get('given_name') ?? PlaceholderString::NOT_PROVIDED,
 'last_name' => $payload->get('family_name') ?? PlaceholderString::NOT_PROVIDED,

//createUserAccount()

'email' => $payload->get('email'),
'photo' => $payload->get('picture') ?? null,
'google_id' => $payload->get('sub'),
```

It works fine again

**Comment by C-Ivan-Bandilla** [comment]
It is now working both sign in and sign up in facebook and google

**Pull request merged**
