### PR TITLE
Build/websocket

### PR DESCRIPTION
**Pull request by C-Ivan-Bandilla**
Installed backend websocket dependencies laravel broadcasting using laravel reverb #24 
Websocket credentials are auto generated with some needs to be correct while others are random keys

Installed client side packages to interact with websocket connection #20 

configured **vite.config.js** to resolve packages in vendor folded not sure if there could issue in production configs #23 
```
    resolve: {
        alias: {
            'laravel-echo': '/vendor/node_modules/laravel-echo/dist/echo.js',
            'pusher-js': '/vendor/node_modules/pusher-js/dist/web/pusher.js',
        },
    },
```

```
REVERB_APP_ID=******
REVERB_APP_KEY=*******
REVERB_APP_SECRET=********
REVERB_HOST="localhost"
REVERB_PORT=8080
REVERB_SCHEME=http

VITE_REVERB_APP_KEY="${REVERB_APP_KEY}"
VITE_REVERB_HOST="${REVERB_HOST}"
VITE_REVERB_PORT="${REVERB_PORT}"
VITE_REVERB_SCHEME="${REVERB_SCHEME}"
```

To use websocket you may start the server using 

` php artisan reverb:start --debug` or  `php artisan reverb:start `

  You may include script file to establish websocket connection
  `resources\js\websocket.js`

  `

A sample websocket listener is in `resources\js\auth-listener.js`

It is listening to a private websocket channel where authorized current user session is allowed

### CODE REVIEW

**Comment by Carl-Tabuso** [comment]
I don't know if it's a good idea to reveal this:

> REVERB_APP_ID=207797
REVERB_APP_KEY=givrafgeeb8km6oqzzbk
REVERB_APP_SECRET=due2ky8w9usofoh24vjl
REVERB_HOST="localhost"
REVERB_PORT=8080
REVERB_SCHEME=http

**Comment by C-Ivan-Bandilla** [comment]
I have read it somwhere that it is just random credentials made since it is a locally hosted websocket server

I have it redacted but the history exist

**Comment by C-Ivan-Bandilla** [comment]
Documenting these I dunno if I overlook it on laravel documentation but I feel its undocumented

I had to add on boot() of app\Providers\AppServiceProvider.php

BroadcastServiceProvider::class;


had to add on bootstrap\app.php

    ->withBroadcasting(
        __DIR__ . '/../routes/channels.php',
    )

had to add manually the file app\Providers\BroadcastServiceProvider
<?php

namespace App\Providers;

use Illuminate\Support\Facades\Broadcast;
use Illuminate\Support\ServiceProvider;

class BroadcastServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        // Registers the /broadcasting/auth route
        Broadcast::routes();

        // Include the channel authorization callbacks
        require base_path('routes/channels.php');
    }
}

**Comment by C-Ivan-Bandilla** [comment]
Will try to delay or optimize tomorrow

https://drive.google.com/file/d/1fMrE2qa21vwrS-PVBETj9iJCiR0QW4Qx/view?usp=sharing

**Comment by C-Ivan-Bandilla** [comment]
I forgot to push the update

**Review by Carl-Tabuso — APPROVED** [review]

**Pull request merged**
