### PR TITLE
chore: update to smaller font-sizes

### PR DESCRIPTION
**Pull request by C-Ivan-Bandilla**
### 🛠 Changes
Made font size smaller on common font sizes

### ✨ Context
To make room content, more items visible on screen

### 🧠 Rationale
Other might find font small but they can adjust the font size on their device or browser settings

### 📸 Screenshots (Optional)
Powerlane-Job-Listings-10-26-2024_07_37_PM

Screenshot 2024-10-26 193834

Home-Page-10-26-2024_07_40_PM

### ✔️ Checklist
This is a set of criteria to ensure the correctness of your PR. Check each that applied.
- [x] Is `staging` the base branch of this PR?
- [x] Do your changes not reveal sensitive information, such as secrets, API keys, etc?
- [x] Are there no erroneous console logs, debuggers, or leftover code in your changes?

### CODE REVIEW

**Comment by Carl-Tabuso** [comment]
what is the command to recompile this to CSS?

**Comment by C-Ivan-Bandilla** [comment]
I just 
image
cllick the watching 

then click again to reenable

IF using the live sass compiler 


I didn't include the CSS to reduce likelihood of merge conflict

**Review by Carl-Tabuso — APPROVED** [review]
highly suggest to flex end these navlinks

image

**Comment by C-Ivan-Bandilla** [comment]
image
I think the justify-content-between would be fine
I just need to reduce the column gap
image

**Pull request merged**
