### PR TITLE
feat: leave module

### PR DESCRIPTION
**Pull request by Carl-Tabuso**
### 🛠 Changes

- Leave module seems to be available now, although there weren't much authorization and middleware checks.
- Can now request, approve, and deny.

image

### ✔️ Checklist

- [x] Is `staging` the base branch of this PR?
- [x] Do your changes not reveal sensitive information, such as secrets, API keys, etc?
- [x] Are there no erroneous console logs, debuggers, or leftover code in your changes?

### CODE REVIEW

**Comment by C-Ivan-Bandilla** [comment]
How  this works?

On Employee of Accouting
image

image

Manager of accounting

image
image

**Comment by Carl-Tabuso** [comment]
how did you get to that division by zero error. Can yu provide reproducible steps?

How this leave module works is basically the first two approvals should be the supervisor and dept head/manager. The remaining two will be from the hr department.

**Comment by Carl-Tabuso** [comment]
i think im completely off. The issue might be perhaps when viewing your own request.

**Comment by C-Ivan-Bandilla** [comment]
https://drive.google.com/file/d/1f4psIldjT0rR3zuZ44l6NXH3i_Piw_wv/view?usp=sharing

https://drive.google.com/file/d/1f7LcWbn2KTfQUz2YaYnswPwLs7y8aaQA/view?usp=sharing

https://drive.google.com/file/d/1fA39qmVnMfzgTMsra6l2JCoMnXZq47Zy/view?usp=sharing

**Comment by Carl-Tabuso** [comment]
found out that it's due to how my eloquent query is structured. What happens basically is that illuminate paginator is trying to divide by zero if my `$query->count()` returns so. The logic of the query itself is flawed. Will work on this.

**Comment by Carl-Tabuso** [comment]
Up for review again @C-Ivan-Bandilla

**Comment by C-Ivan-Bandilla** [comment]
Am I doing it incorrectly

request from employee 1

then login ias manegerial employee 6

maybe I don't have approvers

image


but when I click here

image

I get

image


the viewing of the owner of request works now

**Review by C-Ivan-Bandilla — APPROVED** [review]

**Pull request merged**
