### PR TITLE
Calendar

### PR DESCRIPTION
**Pull request by biellamariscotes**
### Ctrl+f  and type "Replace" or "Back-end Replace" to easily see what needs to be handled / "Back-end Replace Note" to read important notes!

> [!NOTE]  
> - Just needs retrieving of data from db.

### 🛠 Changes

- Installed a new package for calendar: **FullCalendar**. Check [docs](https://fullcalendar.io/docs) of the library.

### 🧠 Rationale
- Didn't continue with the **livewire-calendar** and went with **FullCalendar** instead due to the ease of customization and better support for the calendar functionality.

### 🦶 Steps
- Run `npm install` in terminal.
- Always include the script/import the scss partial of the calendar on the main blade/scss file if the page requires.

**For Head Admin:**

```
@vite(['resources/js/calendar.js'])
```

**For Employee:**

```
@vite(['resources/js/employee/calendar.js'])
```

**Use SCSS Partial:**

```
@import '../../calendar';

Note: The directory traversal may vary depending on the location of the file.
```

### 📸 Screenshots (Optional)

**Calendar Manager - Admin**

https://github.com/user-attachments/assets/53de9258-d357-4aa1-8c2e-b30d93ae02bb

**Employee Information Attendance**
image

### 🎥 Demos (Optional)
If you want to provide additional demo recordings, you may do so here.

### ✔️ Checklist
This is a set of criteria to ensure the correctness of your PR. Check each that applied.
- [x] Is `staging` the base branch of this PR?
- [x] Do your changes not reveal sensitive information, such as secrets, API keys, etc?
- [x] Are there no erroneous console logs, debuggers, or leftover code in your changes?

### CODE REVIEW

**Comment by Carl-Tabuso** [comment]
if we're going to proceed with the js package, could you make some cleanup and remove the livewire calendar libraries and unpublish its blade templates. Saw some blade files under `resources/views/vendor/livewire-calendar/`. There's just too much clutter. Also i don't think most of the modal dialog components are being utilized (i don't use them) but i'm not sure about ivan, maybe they can be removed too. I made this reusable modal component `resources/views/components/modals/dialog.blade` which i used almost everywhere now, except performance categories (if i remember correctly).

**Comment by C-Ivan-Bandilla** [comment]
> i'm not sure about ivan,

I use prebuilt modals those with icons  success  email sent etc

**Comment by C-Ivan-Bandilla** [comment]
Did u try restarting the server?
after removing package

image

**Comment by C-Ivan-Bandilla** [comment]
Ow my my apologies I forgot to run npm install part

**Review by C-Ivan-Bandilla — APPROVED** [review]

**Pull request merged**
