### PR TITLE
Livewire Package Installation and Misc

### PR DESCRIPTION
**Pull request by Carl-Tabuso**
## Additions and Changes

- Installed the laravel livewire package. To install locally on your device, simply run `composer update` on terminal
- Uncommented **node_modules** folder in `.gitignore`. It was only included in the push during initial setup for versioning.
- Updated axios version to 1.7.4 in `package.json` to resolve the [dependabot alerts of SSRF](https://github.com/POWERLANE-TEAM/emplo-hrms/security/dependabot/1).
> [!NOTE]
> Although the security alert is fixed in `staging`, it'll only be closed upon merged into the `master`

- Do visit the [laravel livewire documentation](https://livewire.laravel.com/) for creating livewire components

### CODE REVIEW

**Comment by C-Ivan-Bandilla** [comment]
Are you experiencing this in your end too

image

**Comment by C-Ivan-Bandilla** [comment]
the issue isnt present on the staging when I also do fresh clone

image

**Comment by Carl-Tabuso** [comment]
`build/livewire` branch works fine on me. When i read your error message, I see the problem being npm not able to locate the .js file called `dep-BzOvws4Y.js` and I have this on my end.

image

Perhaps u should run `npm update` in this case?

**Comment by C-Ivan-Bandilla** [comment]
I reverted to commit 7e635f1 it is okay
image
image

----
I  executed npm update still

image

**Review by C-Ivan-Bandilla — APPROVED** [review]
The issue is resolved

Tested with simple usage of livewire from docs

csp had blocked the scripts tho  

had to add 

        $this->addDirective(Directive::SCRIPT, 'unsafe-eval');
        
        
image

        
 I’m questioning myself whether CSP remains effective if I configure it to allow this. Haha

**Pull request merged**
