### PR TITLE
chore(components/employee/sidebar): [Important]  Removed old layout being used in the employee sidebar

### PR DESCRIPTION
**Pull request by C-Ivan-Bandilla**
Removed old layout of sidebar and used the new one located at resources\views\components\layout\employee\nav\sidebar

### CODE REVIEW

**Comment by Carl-Tabuso** [comment]
What is this changed for exactly?

**Comment by C-Ivan-Bandilla** [comment]
I noticed that the resources\views\components\layout\employee\nav\sidebar\hr-navs.blade.php component is using the old sidebar components located at components/employee

 but you requested to move them to resources\views\components**\layout**\employee

I copied it to the resources\views\components**\layout**\employee but forgot to delete it
Also they are referencing these old components so I change them
image

**Review by Carl-Tabuso — COMMENTED** [review]
The issue here is you're checking for a role to identify which links should be allowed for a user. But if you remember, there's no direct association of roles to permissions. It should be flexible. My suggestion is that you simply create a single blade file for employees sidebar and you can just simply use the @can directive to know if a user has permission to access a particular resource. This way, you can accommodate a scenario when admin directly assign permission to a user model

**Comment by Carl-Tabuso** [comment]
can you first approve #52 and merge the latest change into this branch?

**Comment by C-Ivan-Bandilla** [comment]
In order to for permission to work properly a permission and also the role needs to be specific in guard

In database\seeders\RolesAndPermissionsSeeder.php
There could be a possibility of same permission for different guard
image

I also temporarily commented out the 
image
since a role can only have permissions similar to its guard


Now this works on resources\views\components\layout\employee\nav\sidebar\hr-navs.blade.php
image
image

 should I proceed with this approach?

**Comment by Carl-Tabuso** [comment]
can u update this branch first. Idk what could happen due to many changes I made in #52 #53

**Comment by Carl-Tabuso** [comment]
Is it really necessary to associate roles and permissions with a guard? I went over the package docs on [using permissions and roles with multiple guards](https://spatie.be/docs/laravel-permission/v6/basic-usage/multiple-guards#content-using-permissions-and-roles-with-multiple-guards) and I don't see a good enough reason not to stick with a default web guard.

The problem I see with using a guard name is it'll introduce redundancies and complexities. We can force the app to use the default guard `protected function getDefaultGuardName(): string { return 'web'; }` according to the docs if there isn't a need to differentiate between guards.

I also see this as an unnecessary overhead since we're trying to implement Policies to handle edge cases, such as an employee having permission to access and modify an applicant's profile or an applicant being able to make changes to his own personal information.

I can't fathom why should we use different guards tbh, it's quite complex for me. Still, wdyt?

**Review by Carl-Tabuso — APPROVED** [review]
For database seeder, u may create a new pull request.

**Comment by C-Ivan-Bandilla** [comment]
The proposed changes isn't here yet

**Comment by Carl-Tabuso** [comment]
open a new pr

**Pull request merged**
