### PR TITLE
Added basic authentication using default laravel fortify authentication

### PR DESCRIPTION
**Pull request by C-Ivan-Bandilla**
Added Signup + email verification
https://drive.google.com/file/d/1fLLFTCSGmLimlKBj7h6IJ-3mvnDFnceW/view?usp=sharing
image

Added login 
No user type restriction yet
https://drive.google.com/file/d/1fLpA_5sXRbQCIzwQ3oLKrCdQR6Itx2Dl/view?usp=sharing

### Bugs
Going back and forth across pages result mess in assets
https://drive.google.com/file/d/1fLqY3sUDT_nhzLvkv_GSZ3WBbzWZXPIH/view?usp=sharing

### CODE REVIEW

**Comment by Carl-Tabuso** [comment]
Why is my previous commits history merged into `staging` included in here?

**Comment by C-Ivan-Bandilla** [comment]
maybe because of unintended squash and merge should have look closely before merging

**Comment by Carl-Tabuso** [comment]
just to be safe, let's remain with merge commit.

**Review by Carl-Tabuso — APPROVED** [review]
Hopes this doesn't break anything.

**Pull request merged**
