### PR TITLE
chore(model/migration): ph address and performance evaluations

### PR DESCRIPTION
**Pull request by Carl-Tabuso**
This pull request contains an installed package: [laravel excel](https://docs.laravel-excel.com/3.1/getting-started/) used to extract contents from [PSGC 2024 publication file](https://github.com/POWERLANE-TEAM/emplo-hrms/blob/chore/psgc-address-and-rbac/storage/PSGC-2Q-2024-Publication-Datafile-rev.xlsx) containing the updated master list of every regions, provinces, cities, and barangays in the Philippines, downloaded from PSA's [PSGC database.](https://psa.gov.ph/classification/psgc) This PR also contains the changes on models and migration files for performance evaluations.

### Ph Administrative Divisions

- I created a migration file containing the tables for `Regions` `Provinces` `Cities/Mun/SubMun`, `Barangays`, and a seeder file that maps the heading names and identifies which sheet to extract contents from.
- I followed the coding structure used by the Philippine Standard Geographic Code to identify which provinces are under the jurisdiction of which regions, and likewise for provinces -> cities -> barangays.
- You should run a fresh migration and seed your database again. The table row counts should be **18** for `regions` **82** for `provinces` **1,656** for `cities` — including municipalities/sub municipalities and **42,004** for `barangays`.
- You can do this in one go by running `php artisan migrate:fresh --seed` or `php artisan db:seed --class=PsgcSeeder` if you want to manually seed the 4 tables simultaneously.

> [!WARNING]
> To use the export/import functionality of excel package, locate your php.ini configuration file and uncomment `;extension=gd` and `;extension=zip` by removing the semicolon `;`

### Migrations

- `performance_categories` will store the parameters defined by Powerlane.
- `performance_ratings` will allow for defining rating and scales to evaluate the parameters which the employee will be evaluated against.
- `performance_periods` will store how often the evaluation occur (e.g: "Third Month", "Fifth Month", etc).
- `performance_details` will store the process and period undertaken by Powerlane such as the supervisor, area manager's signing/approval of the evaluation made.
- `performance_category_ratings` will be the pivot table that links parameters(performance_categories) and ratings(performance_ratings) to determine employee performance, and additionally, as a link to essential details(performance_datails).

### Backed Enums

- For type safety purposes, I created backed enums located on `app/Enums/` directory.
- They are for accessing different cases of user's status, roles, and permissions.

### Roles and Permissions

- I created a new seeder file with draft/initial roles and permissions in `app/database/seeders/RolesAndPermissionsSeeder.php`.
- The values for roles and permissions are assigned using enum cases, referencing the actual string values (lowercase) to be stored in the database.

## To-dos

- [x] Write sample roles and permission to test on route-level middleware using laravel-permission package.
- [x] Provide a demo of route-level middleware authorization.

### Test Cases

- Route-level middleware using permission checks for each predefined roles, such as `basic level` `intermediate level` `advanced level` can be accessed in `tests/Feature/RouteMiddlewareAuthorizationTest.php`
- To register the get requests on routes, I created fake URIs and a single blade template.
- I tested the ff:
   - Basic level shouldn't be able/have permission to access the employee dashboard.
   - Intermediate level should be able/have permission to view employee information.
   - Advanced level should be able to/have permission to access resource only available to its role.

#### Running the [test script](https://github.com/POWERLANE-TEAM/emplo-hrms/blob/80ea68be5309f4f82fb6b31f1a98e8364527bda0/tests/Feature/RouteMiddlewareAuthorizationTest.php)

https://github.com/user-attachments/assets/8a58e85f-f316-4dca-937c-fc4d9839b00e

### CODE REVIEW

**Comment by C-Ivan-Bandilla** [comment]
Before running composer update may need to enable gd and zip extension

to locate php.ini `php --ini` 
then uncomment gd and zip
you can edit this for better wording

**Comment by Carl-Tabuso** [comment]
Yes. This kinda slipped my mind while writing the description.

**Comment by C-Ivan-Bandilla** [comment]
Wdyt about this

I add the temporary increase in memory limit to have successful seeding

image

image

**Comment by Carl-Tabuso** [comment]
No prob if this little addition helps. But I'm curious if 512mb memory limit is like some sort of standard or whatever?

**Comment by C-Ivan-Bandilla** [comment]
It isnt but tried 400M is the lowest it can be seed but sometimes it fails on 400 I'd make it 450M

**Review by C-Ivan-Bandilla — APPROVED** [review]

**Pull request merged**
